### ISSUE TITLE
run error  

### ISSUE THREAD

**Issue by myyan** [loomnetwork/truffle-dappchain-example#1]
### step one reset the dappchain

![image](https://user-images.githubusercontent.com/10210390/42411563-91be8c04-8230-11e8-9599-cf1ab6ee2932.png)

### stop two run the dappchain
![image](https://user-images.githubusercontent.com/10210390/42411566-a60b4d0a-8230-11e8-91fb-685b60496fca.png)

### deploy contract to dappchain 
![image](https://user-images.githubusercontent.com/10210390/42411570-c5ed1e28-8230-11e8-9f43-4dd15f4a3abc.png)

![image](https://user-images.githubusercontent.com/10210390/42411572-d08d6130-8230-11e8-8067-f1e9408c3c9b.png)

### start the web 
![image](https://user-images.githubusercontent.com/10210390/42411573-de794e8a-8230-11e8-8338-979485e27114.png)

### result 
![image](https://user-images.githubusercontent.com/10210390/42411575-f039695c-8230-11e8-89f3-b416199ebf33.png)

![image](https://user-images.githubusercontent.com/10210390/42411582-02f90f52-8231-11e8-969a-5aa7908357e5.png)

![image](https://user-images.githubusercontent.com/10210390/42411597-4a02ae44-8231-11e8-9d65-467ccd9fe00f.png)

![image](https://user-images.githubusercontent.com/10210390/42411602-5ba67626-8231-11e8-87db-74d57c074458.png)
![image](https://user-images.githubusercontent.com/10210390/42411612-6953e09c-8231-11e8-96ff-0aaa27c0de8d.png)

**Comment by myyan** [comment]
![image](https://user-images.githubusercontent.com/10210390/42412251-1f3ce1e8-823b-11e8-86c5-142fceb8e572.png)



i run it on the google cloud have some question ,

**Comment by myyan** [comment]
![image](https://user-images.githubusercontent.com/10210390/42412281-e52c6aea-823b-11e8-8ee1-a7b02f8748b8.png)

**Comment by myyan** [comment]
![image](https://user-images.githubusercontent.com/10210390/42412311-92c40f32-823c-11e8-9959-002a427f1e98.png)

**Comment by myyan** [comment]
@eduardonunesp  hi  do you know what's wrong , it seems deploy error ,i refer the truffle doc , but  still don't know how to fix it 
![image](https://user-images.githubusercontent.com/10210390/42415834-f7642e4c-828f-11e8-8ba5-cb11e5bf9743.png)

**Comment by smlee729** [comment]
Same issue here.

**Comment by eduardonunesp** [comment]
@smlee729 @myyan do you guys have the number of the build? `loom version`

**Comment by smlee729** [comment]
`2018/07/08 09:12:58 Sending logs to file://-
1.0.0+b161`

**Comment by smlee729** [comment]
@eduardonunesp @myyan Oops sorry guys. I didn't notice that loom version has been upgraded. 
I copied from loom's developers page, but it seems obsolete.
Now it's working.

`
yarn run v1.7.0
$ truffle deploy --reset --network loom_dapp_chain
Using network 'loom_dapp_chain'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x0365f31ddc3791ef38984b01f932560a790cbfbf829e59643024b6d868003dce
  Migrations: 0x6d002528e54a421f5e7375690e5fb74b75add0d8
Saving successful migration to network...
  ... 0x4841ea8ddaa7e06263d1cf979bf30b4eb0250c3666da74b6f288648f97c0932f
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying SimpleStore...
  ... 0x774e35f3c549e67431cf2d05924fd21d560ef08f522ffdbddc2618d6a8f7ec9a
  SimpleStore: 0x1a31b9b9d281d49001fe7f3f638000a739afc9c3
Saving successful migration to network...
  ... 0x04114dc450dac2d4445d5cf35a21e5244925837dd67ed116ece7be5c91baa993
Saving artifacts...
✨  Done in 9.02s.
`
