### ISSUE TITLE
Command "gen:extdev-key" not found

### ISSUE THREAD

**Issue by zulhfreelancer** [loomnetwork/truffle-dappchain-example#29]
Hi,

I am following your guide [here](https://loomx.io/developers/en/intro-to-loom.html#deploying-your-first-app) and the `yarn gen:extdev-key` command gave me `Command "gen:extdev-key" not found` error.

Hope you can fix the docs or readd the script in this repo.

Thank you.

**Comment by vicnala** [comment]
Hi.
I don't use yarn, but `npm run gen:extdev-key` works for me.

**Comment by OuterGod** [comment]
Has been added on pull request #27
