### ISSUE TITLE
strconv.ParseInt parsing error

### ISSUE THREAD

**Issue by vicnala** [loomnetwork/truffle-dappchain-example#31]
Hi,

I'm on Ubuntu 18. Tried with node 8 and 10 and I get this error when deploying (local or remote):

> Error: ProviderError: JSON-RPC Error -32603 (Internal error): strconv.ParseInt: parsing "0x6e830c"

The hex number changes when retry the deployment.

Thanks for you work!

**Comment by meetsiraja** [comment]
I also have the same issue. Not able to deploy a contract on the network in this example repo. Getting below error,
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'extdev_plasma_us1'
> Network id:      9545242630824
> Block gas limit: 0x0


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x4b16dd7e2e5e804f279e370b5ae010e4bc1115b7983528fa081cafa625a7e729
   ⠼ Blocks: 0            Seconds: 0Error: Error: ProviderError: JSON-RPC Error -32603 (Internal error): strconv.ParseInt: parsing "0x7283ca": invalid syntax
    at Object.run (/Users/yudiz/.nvm/versions/node/v8.16.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at <anonymous>
Truffle v5.0.22 (core: 5.0.22)
Node v8.16.0
```

Any help would be highly appreciated.

**Comment by shunp** [comment]
Me neither.

> Blocks: 2            Seconds: 5Error: Error: ProviderError: JSON-RPC Error -32603 (Internal error): strconv.ParseInt: parsing "0x72e659": invalid syntax

My environment is as follows.
Truffle v5.0.19 (core: 5.0.19)
Node v10.15.3

**Comment by andreipope** [comment]
@vicnala @shunp Are you using `yarn` or `npm`?

**Comment by shunp** [comment]
@andreipope I tried both `yarn` and `npm`, but I failed when I executed `yarn deploy:extdev`. 
However I succeeded in deploying contracts using the same command in `gateway-tutorial` project.

**Comment by andreipope** [comment]
@shunp Could you join our Developer Chat https://t.me/loomnetworkdev? It would be easier to debug it there.
