### ISSUE TITLE
typo? rinkey

### ISSUE THREAD

**Issue by masary2989** [loomnetwork/truffle-dappchain-example#9]

**Comment by masary2989** [comment]
In gateway-cli 
`function loadRinkeyAccount() {`
maybe Rinkey =>Rinkeby


I think it is fine but perhaps it is better to fix it

**Comment by masary2989** [comment]
If it is troublesome please close it because it works without problems

**Comment by eduardonunesp** [comment]
Thanks @masary2989 we're going to fix that typo
